# spring.sql.init.mode=always
# spring.datasource.url=jdbc:postgresql://localhost:5432/unicorns
# spring.datasource.password=postgres
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.error.include-message=always
spring.jpa.open-in-view=false
spring.datasource.hikari.maximumPoolSize=1
spring.datasource.hikari.data-source-properties.preparedStatementCacheQueries=0
management.endpoint.health.probes.enabled=true

# Disable Hibernate usage of JDBC metadata
hibernate.boot.allow_jdbc_metadata_access=false

# Database initialization will typically be performed outside of Spring lifecycle
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.allow-pool-suspension=true

# Connect to database usign credential from AWS SecretsManager
spring.datasource.driver-class-name=com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
spring.datasource.username=unicorn-store-db-secret

# wait for database connection for 30 sec
# spring.datasource.hikari.connection-timeout=30000
# spring.datasource.hikari.initialization-fail-timeout=30000
